### ISSUE TITLE
Orientation Sensor

### ISSUE THREAD

**Issue by ghost** [TrekDev/Xamarin.Android.Skobbler#2]
Hello!

Using the demo, without any modification, the method StartOrientationSensor has an Unhandled Exception:
System.InvalidCastException: Cannot cast from source type to destination type.

Thank you very much for all your work!

**Comment by jeremy-ellis-tech** [comment]
Hi ruiamorimwDev,

Thanks for bringing this up. It looks like this was because I used the incorrect sensor listener interface. [I have pushed a fix](https://github.com/TrekDev/Xamarin.Android.Skobbler/commit/3b9b6e7466528edb3108d39bc4719b40fcaa8010)

Just to make sure, can you confirm this has fixed it for you?

Thanks,

-TD

**Comment by ghost** [comment]
Hi TrekDev,

It's fixed!

Thank you!
Rui
